# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyKkumi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyKkumi

  target 'MyKkumiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyKkumiUITests' do
    # Pods for testing
  end

pod 'RxSwift'
pod 'RxCocoa'
pod 'Alamofire'
pod 'Moya/RxSwift'
pod 'Swinject'

end
