name: iOS feature unitTest workflow

on:
  push:
    branches: [ feature/* ]
  pull_request:
    branches: [ feature/* ]
  workflow_dispatch : 

jobs:
  build:
    runs-on : macos-latest

    steps:
    - uses : actions/checkout@v3
    - name : install CocoaPods
      run: |
        cd Mykkumi
        pod install
        
    - name : Build Xcode
      run: |
        xcodebuild clean test -workspace MyKkumi/MyKkumi.xcworkspace \
        -scheme MyKkumi \
        -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'

    
